coverage:
  precision: 2
  round: up
  range: "70...100"
  notify:
    require_ci_to_pass: yes

  status:
    project: yes
    patch: yes
    changes: yes

comment:
  layout: "header, diff, changes"
  behavior: default
